### ISSUE TITLE
Maintain formatting?

### ISSUE THREAD

**Issue by shimizurei** [polm/cutlet#23]
Hello, 

Is it possible to maintain the formatting of input text? I like to structure Japanese lyrics for transliteration purposes, but have found that there are no services that maintain the formatting (other than RomajiDesu but it doesn't do Hepburn), so I usually end up with a huge block of text.

![Screenshot 2021-04-16 07 15 58](https://user-images.githubusercontent.com/3500094/115017188-1f201500-9e84-11eb-8988-0b56585493a0.png)

**Comment by polm** [comment]
Hm, I hadn't considered that newlines and other whitespace are removed. 

I don't think preserving that makes sense as a default cutlet feature, but it's pretty easy to add by preprocessing, so I could put it in the demo. 

Also, when reporting an issue with specific input, please include sample text I can use for testing.

**Comment by shimizurei** [comment]
Sorry, I figured it was easy enough to replicate since all I did was add new lines to your default text in order to test the feature out initially. My text is just there to show my use case.

Thank you for considering the addition.

**Comment by polm** [comment]
OK, the [demo][] has been updated to preserve formatting. The changes are pretty simple, you can [check the source][source]. 

[demo]: https://share.streamlit.io/polm/cutlet-demo/main/demo.py
[source]: https://github.com/polm/cutlet-demo/blob/main/demo.py
