### ISSUE TITLE
Cutlet converts こんにちは to Konnichiha instead of Konnichiwa

### ISSUE THREAD

**Issue by whiteeat** [polm/cutlet#33]
Cutlet converts こんにちは to Konnichiha instead of Konnichiwa, is it an intentional behaviour or a bug? Because こんにちは should be read as Konnichiwa.
![こんにちはGoogle](https://user-images.githubusercontent.com/10330544/217890880-c09f1cac-aae3-4ed7-93d0-cae39cf1648f.png)
![こんにちはCutlet](https://user-images.githubusercontent.com/10330544/217890974-72bf3bca-2e10-438e-813a-177a93eb56e7.png)

**Comment by polm** [comment]
Thanks for reporting that. The issue seems to be that in UniDic 「こんにちは」 is a single token, so it's not possible to recognize the は as the particle in the usual fashion. 

If this is an issue for your application, I would recommend registering an exception for こんにちは, as outlined in the README.

**Comment by polm** [comment]
This should be resolved in the demo now.
