### ISSUE TITLE
Is it possible to generate furigana for Kanji using this library?

### ISSUE THREAD

**Issue by FlippFuzz** [polm/cutlet#37]
It would be a nice feature. 
Hopefully, this is possible because we are already generating the romaji.

**Comment by polm** [comment]
If you want furigana, you don't need this library unless you want your furigana to be romaji, you can use fugashi directly. Something like this:

```
import fugashi

tagger = fugashi.Tagger()
kana = [nn.feature.kana for nn in tagger("吾輩は猫である")]
# => ['ワガハイ', 'ハ', 'ネコ', 'デ', 'アル']
```

The output will be katakana, not hiragana, but that can be easily converted.

**Comment by polm** [comment]
Closing since this should be resolved, but feel free to follow up if you still have questions.
