### ISSUE TITLE
Python < 3.7 support & possible bug

### ISSUE THREAD

**Issue by krackers** [polm/cutlet#4]
The use of `str.isascii` currently limits it to python 3.7+. Since this is only used in one spot, it seems like you could use a polyfill similar to:

```
try:
   s.encode('ascii');
   return True
except UnicodeEncodeError:
   return False
```

I'm also seeing an issue where "私は" gets converted to '代名詞 wa'

**Comment by polm** [comment]
Thanks for the notes, I didn't realize that about `isascii`. 

Also thanks for the note on 私. The foreign lemma feature of Unidic is undocumented, and while there's a lot of words with good data I'd previously run into words where the foreign lemma is just 外国. It looks like 私, 君, and 余 have lemmas like "私-代名詞", but other similar words like 僕 don't have that.
