### ISSUE TITLE
Was the streamlit app removed?

### ISSUE THREAD

**Issue by shimizurei** [polm/cutlet#44]
This is what I see when I go to the link https://share.streamlit.io/polm/cutlet-demo/main/demo.py

![image](https://github.com/polm/cutlet/assets/3500094/3b86cb3d-b654-4146-8ded-ded90f4c45dd)

**Comment by polm** [comment]
Thanks for letting me know. I didn't change anything or receive any notice from Streamlit, but apparently the URL changed at some point. It looks like this is the new URL:

https://polm-cutlet-demo-demo-0tur8v.streamlit.app/

**Comment by polm** [comment]
This should be resolved with the new link, thanks again for reporting it.
