### ISSUE TITLE
Converting to romanji when the text is tokenized

### ISSUE THREAD

**Issue by echan00** [polm/cutlet#45]
Hi Paul

Thanks for the awesome library. I have a problem where I'm trying to convert a tokenized Japanese text to Romanji. 

" 何人ですか ?" is correctly "Nanijindesu ka"?

But if i tokenize the text to [何, 人, ですか, ?] and convert each token to romanji it is incorrect because the text is missing. 

How would I covert Japanese text to Romanji so I can get two matching tokenized arrays?

**Comment by polm** [comment]
Glad you're enjoying the library. Please note the word "romaji" has no "n". 

何人ですか would normally be read "Nannin desu ka" ("How many people?"). "Nanijin" is also valid but drastically less common.

If you need aligned tokens and romaji you can use the [`romaji_tokens` functionality](https://polm.github.io/cutlet/cutlet.html#Cutlet.romaji_tokens) that was added recently. 

```
import cutlet

katsu = cutlet.Cutlet()
words = cutlet.tagger(cutlet.normalize_text("何人ですか"))
toks = katsu.romaji_tokens(words)

for tok, word in zip(toks, words):
    print(word.surface, tok.surface, sep="\t")
```

**Comment by echan00** [comment]
Oh you're a life saver. Am I missing something? 

`AttributeError: module 'cutlet' has no attribute 'tagger'`

**Comment by polm** [comment]
Sorry, there was a mistake in the example code. It should be `katsu.tagger` - the tagger object is on the instance, not the class.

**Comment by echan00** [comment]
Amaze balls!
