### ISSUE TITLE
Cutlet port in Java

### ISSUE THREAD

**Issue by asaval** [polm/cutlet#61]
Hi, thank you for your great work on Cutlet.
I'm currently looking for a library in Java to convert Japanese to romaji for a personal project in an android app I develop.
I know that there are already some libraries available but after some tests, Cutlet seems to better match my needs.
Thus, I decided to work on a port of Cutlet in Java. After some work, first results seem to be good enough. 
My port is just a first draft at the moment but it might be useful to others.
Since you are the Cutlet's author and my changes are quite marginal in front of your work and your original ideas, I would like to know your feelings about publishing on GitHub the Java port I worked on.
In any case, thanks again for your work!

**Comment by polm** [comment]
Glad to hear you find Cutlet useful!

Please feel free to make a Java version following the terms of the license. You can just add a copyright line below the existing one, copying the format and adding your name. 

The only other things I'd request is that you link to the cutlet repo in the README and that it's clear to users that issues with the Java version should be reported to you, not at this repo. If you could post a link to your project in this issue that would also be great.

**Comment by asaval** [comment]
I agree with your terms. I will prepare the Java version following your terms and keep you updated in this issue when it's ready.

**Comment by polm** [comment]
Given the lack of updates I am going to close this, but if you make progress on it please feel free to follow up here or in a new issue/PR.
