### ISSUE TITLE
Can't use web demo on mobile due to Ctrl+Enter requirement

### ISSUE THREAD

**Issue by j9d3it** [polm/cutlet#63]
Please add a Submit button instead of requiring Ctrl+Enter.

**Comment by polm** [comment]
Thanks for mentioning that, that's a great point.

However, do note that on mobile, clicking outside of the text area cause the form to submit. This is definitely not clear, so I will see about adding a button.

**Comment by polm** [comment]
I added a note to the UI to make this clear, since it seemed better than adding a button.
